```yaml
openapi: 3.0.0
info:
  title: OpenWeatherMap API (Sample)
  version: 1.0.0
  description: Sample OpenAPI definition for OpenWeatherMap /weather endpoint.
servers:
  - url: https://api.openweathermap.org/data/2.5
paths:
  /weather:
    get:
      summary: Get current weather data
      description: Returns current weather data for a city.
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: appid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Invalid API key
        '404':
          description: Not found